<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		<UseWindowsForms>true</UseWindowsForms>
		<DisableWinExeOutputInference>true</DisableWinExeOutputInference>
		<StartupObject>PokeGamingStore.Program</StartupObject>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MSTest.TestAdapter" Version="4.2.2" />
		<PackageReference Include="MSTest.TestFramework" Version="4.2.2" />
	</ItemGroup>
	<ItemGroup>
		<None Update="config.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>